controllers:
    resource: ../src/Controller/
    type: attribute

api_controllers:
    resource: ../src/Controller/Api/
    type: annotation
    prefix: /api


api_login:
    methods: [POST]
    path: /api/login